version: 2
updates:
- package-ecosystem: actions
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
- package-ecosystem: nuget
  directory: "/samples"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
- package-ecosystem: nuget
  directory: "/src"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
