name: Sample Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest  

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core 3.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.x

    - name: Install .NET 5.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.x

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore/Build the sample
      run: msbuild LoginApp.sln /t:restore,build /p:Configuration=$env:Configuration
      working-directory: Sample
      env:
        Configuration: ${{ matrix.configuration }}

    # Execute all unit tests in the solution
    - name: Execute unit tests
      working-directory: Sample
      run: dotnet test LoginApp.sln

